program/tests/program_test/mod.rs
program/tests/test_spot_markets.rs

The referral rebate of 1/5th of the taker fee was not taken into account
before.

Tests: fix test_match_spot_order()

---

program/tests/program_test/mod.rs
program/tests/test_compute.rs
program/tests/test_delegate.rs
program/tests/test_deposit.rs
program/tests/test_funding_rate.rs
program/tests/test_interest_rate.rs
program/tests/test_liquidation.rs
program/tests/test_perp_markets.rs
program/tests/test_perp_trigger_orders.rs
program/tests/test_sanity.rs
program/tests/test_spot_markets.rs
program/tests/test_worst_case.rs

The log scope for these changed in solana 1.9

Tests: Fix program log output

---

.cargo/audit.toml
.github/workflows/ci-cargo-audit.yml
.github/workflows/ci-lint-test.yml

This PR covers two new features:
1. Cargo Audit: automated scanning of Cargo crates for vulnerable dependencies
2. Soteria: automated smart contract vulnerability scanning
Cargo audit:
New GitHub action along with the .cargo/audit.toml configuration file that provides arguments for cargo audit. The config file is handy for e.g. ignores and tracking that with change control.
Soteria:
Built out the existing CI job to include Soteria as well as a couple of other minor tweaks as the job was breaking. Soteria requires Solana and bpf to be installed, so it's a sensible place to run it at the end of other tests.

Soteria and Cargo Audit Automation

---

program/src/instruction.rs

Signed-off-by: microwavedcola1 <microwavedcola@gmail.com>

Fix instruction builder, owner will pay, and his lamports would need to be adjusted

---

.github/workflows/program.yml

CI: add apt-get update

---

README.md

If you like we can rename branches together.

Document branches in the readme

---

.cargo/audit.toml
.github/workflows/ci-lint-test.yml
.github/workflows/ci-soteria.yml

PR contents:
1. Decouple Soteria from the lint/test job for separation of test outcomes (e.g. failure) and performance by running in parallel
2. New ignore to cargo audit config. Vulnerable crate has been reported upstream

Soteria and Audit updates

---

program/Cargo.toml
program/src/processor.rs
program/src/state.rs

This makes it easier to use the HealthCache externally, which I use for the liquidatable-accounts-feed.

HealthCache: improvements for external use

---

mango-logs/src/lib.rs
program/src/processor.rs

Allows for more efficient/robust queries.

Add perp balances logging

---

Cargo.lock
mango-logs/Cargo.toml
mango-logs/src/lib.rs
program/Cargo.toml
program/src/matching.rs
program/src/processor.rs
program/src/utils.rs
program/tests/program_test/mod.rs
program/tests/test_compute.rs
program/tests/test_consume_events.rs
program/tests/test_create_account.rs
program/tests/test_delegate.rs
program/tests/test_deposit.rs
program/tests/test_funding_rate.rs
program/tests/test_interest_rate.rs
program/tests/test_liquidation.rs
program/tests/test_perp_markets.rs
program/tests/test_perp_trigger_orders.rs
program/tests/test_sanity.rs
program/tests/test_spot_markets.rs
program/tests/test_worst_case.rs

DON'T MERGE YET: I want to manually squash some of these commits

Fix memory issues due to event logging, increase consume event processing limit to 8

---

program/src/matching.rs

@ckamm I did a check and I think this doesn't have any side consequences. Can you also check?

make time in force exclusive of expiry_timestamp

---

program/src/matching.rs

Fixed bug where expired orders would create OutEvent but would not be removed because new_bid/new_ask don't reach the part of the code where they are removed from book

post only bug

---

program/src/matching.rs

Feel free to merge after review

Add back deprecated BookSide::iter()

---

Cargo.lock
changelog.md
program/Cargo.toml

Feel free to merge after review

Bump version to 3.4.0, add changelog

---

program/src/state.rs
program/src/utils.rs

program: add helper functions for interest/deposit rate calculation

---

program/src/processor.rs

this is supposed to enable closing out a whole account in a single tx

allow settle fees to silently fail

---

program/src/instruction.rs
program/src/processor.rs
program/tests/program_test/assertions.rs
program/tests/program_test/mod.rs
program/tests/test_spot_markets.rs

implemented cancel all spot orders instruction.

implementing cancel all spot orders instruction

---

program/src/instruction.rs

Signed-off-by: microwavedcola1 <microwavedcola@gmail.com>
There was no helper for composers, added that, acammm has already tested it, works fine.

add place_spot_order2 builder

---

.github/workflows/ci-uxd.yml

Disable UXD CI until we open source

---

program/src/instruction.rs
program/src/processor.rs

Mark MangoCache and RootBank as writable

---

changelog.md
mango-logs/src/lib.rs
program/src/error.rs
program/src/instruction.rs
program/src/matching.rs
program/src/processor.rs
program/src/state.rs
program/tests/program_test/cookies.rs
program/tests/program_test/mod.rs
program/tests/program_test/scenarios.rs
program/tests/test_borrow_withdraw.rs
program/tests/test_liquidation_delisting_token.rs
program/tests/test_spot_market_mode_closeonly.rs

This is still a work in progress and all functions have not been implemented and safety has not been verified.

Delist Market

---

program/src/instruction.rs
program/src/matching.rs
program/src/processor.rs
program/src/state.rs

- Adds an optional second taker fee tier
- Adds a new instruction `change_referral_fee_params2` to set the second fee tier parameters

Add second fee tier

---

program/src/processor.rs

* Allow delegate to close spot open orders accounts and receive lamports

Allow delegate to close spot open orders accounts
