blockworks-foundation/mango-v3

program/src/entrypoint.rs
program/src/processor.rs
program/src/state.rs

It's sufficient to propagate the lifetimes on `checked_unpack_open_orders`.

Fix test build: don't require &'a [AccountInfo<'a>] lifetimes

---

program/src/instruction.rs
program/src/matching.rs
program/src/state.rs
program/tests/test_instructions.rs

Previously, these enums were serialized into four bytes - deserialization expects one.
NOTE: Will add tests. Would be surprising if this was actually broken, maybe I'm just missing a setting?
@dafyddd

Fix serialization of instructions to match MangoInstruction::unpack()

---

program/src/lib.rs
program/src/matching.rs

Because it forces use of non-stable compilers.

Avoid using the destructuring_assignment feature

---

program/src/instruction.rs
program/src/processor.rs
program/tests/test_worst_case.rs

allow listing perp before spot market for base tokens with arbitrary decimals

prepare avax perp listing

---

program/tests/test_perp_trigger_orders.rs

The price difference between execution price and oracle price was too
big given the recently added safety checks.

Fix the perp trigger test

---

program/tests/test_perp_trigger_orders.rs

With this patch 5 out of 5 CI runs passed.

Fix test_perp_trigger_orders reliability

---

program/src/instruction.rs

`clock_ai` account is specified in the instruction interface, however it's not used in the processor.
The withdraw ix will work under some conditions, while the `clock_ai` might be interpreted as an `open_orders` account, and cause the ix to fail.
```rust
let (fixed_ais, open_orders_ais) = array_refs![accounts, NUM_FIXED, MAX_PAIRS];
let [
mango_group_ai,     // read
mango_account_ai,   // write
owner_ai,           // read
mango_cache_ai,     // read
root_bank_ai,       // read
node_bank_ai,       // write
vault_ai,           // write
token_account_ai,   // write
signer_ai,          // read
token_prog_ai,      // read
] = fixed_ais;
```

fix: remove unused account from ix interface spec

---

program/src/instruction.rs
program/src/processor.rs
program/tests/program_test/mod.rs
program/tests/test_create_account.rs

Add a new optional account to
- create_mango_account
- create_spot_open_orders
that pays for the creation of the new account.
If you want to compose on mango and have a PDA account as an owner, it's
impossible to also use it as a payer because accounts with data cannot
pay for PDA creation.

add payer accounts to pda-creation instructions

---

.github/workflows/ci-soteria.yml

PR contains changes that reduces the job run time significantly based on:
1. Updating toolchain without running `build cargo-bpf`
2. Caching Solana binaries and build deps
Job is set to pass until completion of audit/finding review

CI: Soteria performance improvements

---

program/src/matching.rs
program/src/processor.rs
program/src/state.rs

We saw memory allocation failures with six events being processed.

Reduce max number of consumed events further

---

program/tests/program_test/scenarios.rs
program/tests/test_liquidation_perp_market_max_cu.rs
program/tests/test_liquidation_token_and_perp_max_cu.rs
program/tests/test_liquidation_token_and_token_max_cu.rs
program/tests/test_perp_markets.rs

These tests are not detailed enough to detect subtle bugs, but will catch big things like the div-by-zero issue.

Add tests for perp order types

---

Cargo.lock
program/src/instruction.rs

Fixes https://github.com/blockworks-foundation/mango-v3/issues/153
Signed-off-by: microwavedcola1 <microwavedcola@gmail.com>

group doesnt need to be writable in ix builder for withdraw

---

program/src/state.rs

double valid interval for price cache--it's low risk and should help with the number of InvalidPriceCache we get during network instability

double valid interval for PriceCache

---

program/src/processor.rs
program/src/state.rs

Pyth status checks completely freeze the system which is more dangerous than errant publisher. We still have conf interval checks

Remove pyth status check and slot validity entirely

---

.github/workflows/ci-uxd.yml

- Update target branch
- Updated Mango org secret with a new PAT
This is now targeting back the main branch, and run the unit tests successfully.
Previous issue was that someone internally removed the Token permissions. 
Sorry for the inconvenience and thanks again for having our little CI part of 🥭 repo

Update CI (and updated secret PAT)

---

Cargo.lock
program/Cargo.toml

Recently the mango fork of `serum_dex` was [merged](https://github.com/blockworks-foundation/serum-dex/commit/7f55a5ef5f7937b74381a3124021a261cd7d7283) with the upstream version 0.5.5. 
The main mango program is importing the `serum_dex` package with version `0.4.0` from a git repository.
If you delete Cargo.lock, the build will fail with 
```
cargo build-bpf
Failed to obtain package metadata: `cargo metadata` exited with an error:     Updating git repository `https://github.com/blockworks-foundation/serum-dex.git`
error: failed to select a version for the requirement `serum_dex = "^0.4.0"`
candidate versions found which didn't match: 0.5.5
location searched: Git repository https://github.com/blockworks-foundation/serum-dex.git
required by package `mango v3.4.3 …
```

Load serum_dex dependency with a commit ref

---

Cargo.lock
common/Cargo.toml
mango-macro/Cargo.toml
program/Cargo.toml

This reverts commit a12a55947632764a31274c24a41af3aed68c944b.

Revert "Allow solana dependecies above `1.10` (#174)"

---

Anchor.toml
Cargo.lock
common/Cargo.toml
mango-logs/Cargo.toml
mango-macro/Cargo.toml
program/Cargo.toml

Need to upgrade to anchor 0.24.2 or other libs that use mango won't work
Also removed <1.10 limitation on solana packages
already deployed to devnet

upgraded anchor and solana

---

.cargo/audit.toml
changelog.md
program/src/instruction.rs
program/src/matching.rs
program/src/processor.rs
program/tests/program_test/mod.rs

This makes it easier to use TIF when the solana cluster clock does not match the actual clock.
It's not a perfect substitute, since relative expiry will be relative to transaction execution and not to transaction sending.

PlacePerpOrder2: Add flag to request relative expiry

---

program/src/processor.rs

remove_oracle fails for spot only markets since their market state is always Default. This PR changes the check to look at market pubkey instead, which should be the default if the market has either never been added, or has been removed with remove_spot/perp_market

Fix remove_oracle market state checks

---

program/src/state.rs

- Preserve old behaviour if fee tier 2 is not enabled to make simulation return the expected result when triggering advanced orders

Fix perp health taker fee simulation
